mxlib: mx::math::histogramUniform< realT > Class Template Reference
mx::math::histogramUniform< realT > Class Template Reference
General Mathematics
template<typename realT>
class mx::math::histogramUniform< realT >
A histogram with uniform bin spacing.
Calculates the frequency in bins with uniform spacing.
Template Parameters
realT the real data type
Definition at line 24 of file histogramUniform.hpp.
#include <math/histogramUniform.hpp>
Public Member Functions
void setup (realT mn, realT mx, realT w)
Setup the histogram, performing allocations.
void reset ()
Resize and 0 the frequency vector. Assumes _min, _max, and _width are set.
void accum (const realT &val)
Accumulate a value in the appropriate bin.
void accum (const std::vector< realT > &vals)
Accumulate a vector of values.
realT freq (int i)
Get the frequency in the i-th bin.
int bins ()
Get the number of bins.
realT binLeft (int i)
Get the value of the left-edge of the i-th bin.
realT binMid (int i)
Get the value of the middle of the i-th bin.
realT binRight (int i)
Get the value of the right edge of the i-th bin.
void normalize (int excludeTop=0)
Normalize the current frequencies so that the integral over all bins is 1.
Public Attributes
realT _min
The mininum bin location.
realT _max
The maximum bin location.
realT _width
The bin width.
std::vector< realT > _freqs
The frequencies, one for each bin.
Member Function Documentation
template<typename realT > void mx::math::histogramUniform< realT >::accum (const realT & val) inline
Accumulate a value in the appropriate bin.
Parameters
[in] val The value to accumulate
Definition at line 54 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::_min.
Referenced by mx::math::histogramUniform< realT >::accum().
template<typename realT > void mx::math::histogramUniform< realT >::accum (const std::vector< realT > & vals) inline
Accumulate a vector of values.
Parameters
[in] vals The vector of values to accumulate
Definition at line 65 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::accum().
template<typename realT > realT mx::math::histogramUniform< realT >::binLeft (int i) inline
Get the value of the left-edge of the i-th bin.
Returns
the value of the left-edge of the i-th bin.
Parameters
[in] i the bin number
Definition at line 83 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::_width.
template<typename realT > realT mx::math::histogramUniform< realT >::binMid (int i) inline
Get the value of the middle of the i-th bin.
Returns
the value of the middle of the i-th bin.
Parameters
[in] i the bin number
Definition at line 89 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::_width.
template<typename realT > realT mx::math::histogramUniform< realT >::binRight (int i) inline
Get the value of the right edge of the i-th bin.
Returns
the value of the right edge of the i-th bin.
Parameters
[in] i the bin number
Definition at line 95 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::_width.
template<typename realT > int mx::math::histogramUniform< realT >::bins () inline
Get the number of bins.
Returns
the size of the frequency vector.
Definition at line 77 of file histogramUniform.hpp.
template<typename realT > realT mx::math::histogramUniform< realT >::freq (int i) inline
Get the frequency in the i-th bin.
Returns
the current value of _freqs[i].
Parameters
[in] i the bin number
Definition at line 71 of file histogramUniform.hpp.
template<typename realT > void mx::math::histogramUniform< realT >::normalize (int excludeTop = 0) inline
Normalize the current frequencies so that the integral over all bins is 1.
This normalizes the histogram so that it is a probability distribution, such that the sum \(\sum_i P_i \Delta x = 1 \) where \(\Delta x \) is the bin width.
Parameters
[in] excludeTop [optional] specifies a number of bins at the top of the range to exclude from the sum
Definition at line 104 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::_width.
template<typename realT > void mx::math::histogramUniform< realT >::reset () inline
Resize and 0 the frequency vector. Assumes _min, _max, and _width are set.
Definition at line 48 of file histogramUniform.hpp.
Referenced by mx::math::histogramUniform< realT >::setup().
template<typename realT > void mx::math::histogramUniform< realT >::setup (realT mn, realT mx, realT w) inline
Setup the histogram, performing allocations.
Parameters
[in] mn the new minimum bin location
[in] mx the new maximum bin location
[in] w the bin width
Definition at line 35 of file histogramUniform.hpp.
References mx::math::histogramUniform< realT >::reset().
Member Data Documentation
template<typename realT > std::vector<realT> mx::math::histogramUniform< realT >::_freqs
The frequencies, one for each bin.
Definition at line 32 of file histogramUniform.hpp.
template<typename realT > realT mx::math::histogramUniform< realT >::_max
The maximum bin location.
Definition at line 29 of file histogramUniform.hpp.
template<typename realT > realT mx::math::histogramUniform< realT >::_min
The mininum bin location.
Definition at line 28 of file histogramUniform.hpp.
Referenced by mx::math::histogramUniform< realT >::accum().
template<typename realT > realT mx::math::histogramUniform< realT >::_width
The bin width.
Definition at line 30 of file histogramUniform.hpp.
Referenced by mx::math::histogramUniform< realT >::binLeft(), mx::math::histogramUniform< realT >::binMid(), mx::math::histogramUniform< realT >::binRight(), and mx::math::histogramUniform< realT >::normalize().
The documentation for this class was generated from the following file:
math/histogramUniform.hpp