mxlib: mx::psdFilter< _realT > Class Template Reference
mx::psdFilter< _realT > Class Template Reference
Signal Processing » Power Spectra
template<typename _realT>
class mx::psdFilter< _realT >
A class for filtering with PSDs.
Todo:
investigate whether it is really necessary to use the backward transform.
once fftT has a plan interface with pointers for working memory, use it.
Definition at line 27 of file psdFilter.hpp.
#include <psdFilter.hpp>
Public Types
typedef _realT realT
Real floating point type.
typedef std::complex< _realT > complexT
Complex floating point type.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > realArrayT
Eigen array type with Scalar==realT.
typedef Eigen::Array< complexT, Eigen::Dynamic, Eigen::Dynamic > complexArrayT
Eigen array type with Scalar==complexT.
Public Member Functions
psdFilter ()
C'tor.
~psdFilter ()
Destructor.
int rows ()
Get the number of rows in the filter.
int cols ()
Get the number of columns in the filter.
int psdSqrt (realArrayT *npsdSqrt)
Set the sqaure-root of the PSD to be a pointer to an array containing the square root of the PSD.
int psdSqrt (const realArrayT &npsdSqrt)
Set the sqaure-root of the PSD.
int psd (const realArrayT &npsd)
Set the sqaure-root of the PSD from the PSD.
void clear ()
De-allocate all working memory and reset to initial state.
int filter (realArrayT &noise)
Apply the filter.
int operator() (realArrayT &noise)
Apply the filter.
Protected Member Functions
int setSize ()
Set the size of the filter.
Protected Attributes
int _rows
The number of rows in the filter, and the required number of rows in the noise array.
int _cols
The number of columns in the filter, and the required number of columns in the noise array.
realArrayT * _psdSqrt
Pointer to the real array containing the square root of the PSD.
bool _owner
Flag indicates whether or not _psdSqrt was allocated by this instance, and so must be deallocated.
complexArrayT _ftWork
Working memory for the FFT.
fftT< complexT, complexT, 2, 0 > fft_fwd
FFT object for the forward transform.
fftT< complexT, complexT, 2, 0 > fft_back
FFT object for the backward transfsorm.
Member Function Documentation
cols()
template<typename realT > int mx::psdFilter< realT >::cols ()
Get the number of columns in the filter.
Returns
the current value of _cols.
Definition at line 176 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_cols.
filter()
template<typename realT > int mx::psdFilter< realT >::filter (realArrayT & noise)
Apply the filter.
Parameters
[in,out] noise is the noise field of the same size as _sqrtPsd, which is filtered.
Definition at line 248 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_ftWork, mx::psdFilter< _realT >::_psdSqrt, mx::psdFilter< _realT >::fft_back, and mx::psdFilter< _realT >::fft_fwd.
Referenced by mx::psdFilter< _realT >::operator()().
operator()()
template<typename realT > int mx::psdFilter< realT >::operator() (realArrayT & noise)
Apply the filter.
Parameters
[in,out] noise is the noise field of the same size as _sqrtPsd, which is filtered.
Definition at line 274 of file psdFilter.hpp.
References mx::psdFilter< _realT >::filter().
psd()
template<typename realT > int mx::psdFilter< realT >::psd (const realArrayT & npsd)
Set the sqaure-root of the PSD from the PSD.
This allocates _npsdSqrt and fills it with the square root of the values in the array.
Parameters
[in] npsdSqrt an array containing the PSD.
Definition at line 216 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_owner, mx::psdFilter< _realT >::_psdSqrt, and mx::psdFilter< _realT >::setSize().
psdSqrt() [1/2]
template<typename realT > int mx::psdFilter< realT >::psdSqrt (realArrayT * npsdSqrt)
Set the sqaure-root of the PSD to be a pointer to an array containing the square root of the PSD.
This does not allocate _npsdSqrt, it merely points to the specified array, which remains your responsibility for deallocation, etc.
Parameters
[in] npsdSqrt a pointer to an array containing the square root of the PSD.
Definition at line 182 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_owner, mx::psdFilter< _realT >::_psdSqrt, and mx::psdFilter< _realT >::setSize().
psdSqrt() [2/2]
template<typename realT > int mx::psdFilter< realT >::psdSqrt (const realArrayT & npsdSqrt)
Set the sqaure-root of the PSD.
This allocates _npsdSqrt and fills it with th evalues in the array.
Parameters
[in] npsdSqrt an array containing the square root of the PSD.
Definition at line 198 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_owner, mx::psdFilter< _realT >::_psdSqrt, and mx::psdFilter< _realT >::setSize().
rows()
template<typename realT > int mx::psdFilter< realT >::rows ()
Get the number of rows in the filter.
Returns
the current value of _rows.
Definition at line 170 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_rows.
setSize()
template<typename realT > int mx::psdFilter< realT >::setSize () protected
Set the size of the filter.
Handles allocation of the _ftWork array and fftw planning.
Requires _psdSqrt to be set first. This is called by the psdSqrt() and psd() methods.
Definition at line 142 of file psdFilter.hpp.
References mx::psdFilter< _realT >::_cols, mx::psdFilter< _realT >::_ftWork, mx::psdFilter< _realT >::_psdSqrt, mx::psdFilter< _realT >::_rows, mx::psdFilter< _realT >::fft_back, mx::psdFilter< _realT >::fft_fwd, MXE_PARAMNOTSET, and mxError.
Referenced by mx::psdFilter< _realT >::psd(), and mx::psdFilter< _realT >::psdSqrt().
The documentation for this class was generated from the following file:
psdFilter.hpp