mxlib: Geometry and Geodesy
Geometry and Geodesy
General Mathematics
Functions for basic geometry and working with earth coordinate systems.
Functions for basic geometry and working with earth coordinate systems.
#define semilatrect(a, e) (e == 0.0 ? a : (e == 1.0 ? 2.*a : (e < 1. ? a*(1-e*e) : a*(e*e-1))))
Calculate the semi-latus rectum of a conic section
#define focus(a, e) (e == 0.0 ? 1e34 : (e == 1.0 ? 2.*a : (e < 1. ? a*(1-e*e)/e : a*(e*e-1)/e)))
Calculate the focal parameter of a conic section
#define semimaj(p, e) (e == 1.0 ? 1e34 : (e < 1 ? p*e/(1-e*e) : p*e/(e*e-1)))
Calculate the semi-major axis of a conic section, given the focal parameter and the eccentricity.
#define eccent(a, p) (a == 0.0 ? 1e34 : (p >= 1e9 ? 0.0 : (p>0 ? (-p/(2*a)+0.5*std::sqrt(p*p/(a*a) + 4)) : (p/(2*a)+0.5*std::sqrt(p*p/(a*a) + 4)))))
Calculate the eccentricity of a conic section given the semi-major axis and the focal parameter.
template<typename realT >
realT mx::dtor (realT q)
Convert from degrees to radians.
template<typename realT >
realT mx::rtod (realT q)
Convert from radians to degrees.
template<int degrad = 0, typename realT >
realT mx::angleDiff (realT q1, realT q2)
Calculate the difference between two angles, correctly across 0/360.
template<typename realT , int degrad = 0>
realT mx::angleMean (std::vector< realT > &q)
Calculate the mean of a set of angles, correctly across 0/360.
Macro Definition Documentation
eccent
#define eccent (a, p) (a == 0.0 ? 1e34 : (p >= 1e9 ? 0.0 : (p>0 ? (-p/(2*a)+0.5*std::sqrt(p*p/(a*a) + 4)) : (p/(2*a)+0.5*std::sqrt(p*p/(a*a) + 4)))))
Calculate the eccentricity of a conic section given the semi-major axis and the focal parameter.
Definition at line 35 of file geo.hpp.
focus
#define focus (a, e) (e == 0.0 ? 1e34 : (e == 1.0 ? 2.*a : (e < 1. ? a*(1-e*e)/e : a*(e*e-1)/e)))
Calculate the focal parameter of a conic section
Definition at line 29 of file geo.hpp.
semilatrect
#define semilatrect (a, e) (e == 0.0 ? a : (e == 1.0 ? 2.*a : (e < 1. ? a*(1-e*e) : a*(e*e-1))))
Calculate the semi-latus rectum of a conic section
Definition at line 26 of file geo.hpp.
semimaj
#define semimaj (p, e) (e == 1.0 ? 1e34 : (e < 1 ? p*e/(1-e*e) : p*e/(e*e-1)))
Calculate the semi-major axis of a conic section, given the focal parameter and the eccentricity.
Definition at line 32 of file geo.hpp.
Function Documentation
angleDiff()
template<int degrad = 0, typename realT > realT mx::angleDiff (realT q1, realT q2)
Calculate the difference between two angles, correctly across 0/360.
Calculates \(dq = q2- q1 \), but accounts for crossing 0/360. This implies that \(dq \le 180 \).
Parameters
q1 angle to subtract from q2, in degrees.
q2 angle to subtract q1 from, in degrees.
Returns
the difference of q2 and q1
Template Parameters
realT is the type in which to do arithmetic
Definition at line 85 of file geo.hpp.
angleMean()
template<typename realT , int degrad = 0> realT mx::angleMean (std::vector< realT > & q)
Calculate the mean of a set of angles, correctly across 0/360.
Calculates the mean by decomposing into vectors and averaging the components. This accounts for crossing 0/360.
Parameters
q vector of angles to average.
Returns
the mean angle
Template Parameters
degrad controls whether angles are degrees (false) or radians (true)
realT is the type in which to do arithmetic
Definition at line 124 of file geo.hpp.
References mx::astro::constants::c().
dtor()
template<typename realT > realT mx::dtor (realT q)
Convert from degrees to radians.
Uses boost constants:
return q*boost::math::constants::degree<realT>();
Parameters
q is the angle to convert
Returns
the angle q converted to radians
Definition at line 50 of file geo.hpp.
Referenced by mx::improc::ADIDerotator< _realT >::derotAngle(), get_ParAng_deg(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
rtod()
template<typename realT > realT mx::rtod (realT q)
Convert from radians to degrees.
Uses boost constants:
return q*boost::math::constants::radian<realT>();
Parameters
q is the angle to convert
Returns
the angle q converted to degrees
Definition at line 67 of file geo.hpp.
Referenced by get_ParAng_deg().