mxlib: The Kepler Problem
The Kepler Problem
Astronomy » Astrodynamics » Orbital Mechanics
Utilities for solving the Kepler problem.
Utilities for solving the Kepler problem.
Macros
#define KEPLER_TOL (1e-8)
The default tolerance for solutions to the Kepler problem.
#define KEPLER_ITMAX (1000)
The default maximum number of iterations for solutions to the Kepler problem.
Functions
template<typename realT >
long mx::astro::hyperbolic_kepler (realT &E, realT &err, realT e, realT M, realT tol, long itmax)
Solve the hyperbolic kepler equation (for e> 1).
template<typename realT >
realT mx::astro::kepler_danby_1 (realT e, realT M, realT Ei)
Calculate the next iteration of Danby's quartic Newton-Raphson method.
template<typename realT >
long mx::astro::solve_kepler_danby (realT &E, realT &D, realT e, realT M, realT tol, long itmax)
Solve Kepler's equation using Danby's quartic Newton-Raphson method.
template<typename realT >
long mx::astro::solve_kepler (realT &E, realT &D, realT e, realT M, realT tol=KEPLER_TOL, long itmax=KEPLER_ITMAX)
Solve Kepler's equation for any e. Uses solve_kepler_danby if e < 1.0, hyperbolic_kepler otherwise.
Macro Definition Documentation
KEPLER_ITMAX
#define KEPLER_ITMAX (1000)
The default maximum number of iterations for solutions to the Kepler problem.
Definition at line 37 of file kepler.hpp.
Referenced by mx::astro::solve_kepler().
KEPLER_TOL
#define KEPLER_TOL (1e-8)
The default tolerance for solutions to the Kepler problem.
Definition at line 32 of file kepler.hpp.
Referenced by mx::astro::solve_kepler().
Function Documentation
hyperbolic_kepler()
template<typename realT > long mx::astro::hyperbolic_kepler (realT & E, realT & err, realT e, realT M, realT tol, long itmax)
Solve the hyperbolic kepler equation (for e> 1).
Note
this is not tested very well (as of 2014.08.09)
Returns
-1 on exceeding itmax, otherwise reurns the number of iterations.
Template Parameters
realT is the type used for arithmetic
Parameters
[out] E is the eccentric anomaly
[out] err is the error after the last iteration
[in] e is the eccentricity
[in] M is the mean anomaly
[in] tol is the desired tolerance
[in] itmax is the maximum number of iterations
Definition at line 52 of file kepler.hpp.
Referenced by mx::astro::solve_kepler().
kepler_danby_1()
template<typename realT > realT mx::astro::kepler_danby_1 (realT e, realT M, realT Ei)
Calculate the next iteration of Danby's quartic Newton-Raphson method.
Definition at line 89 of file kepler.hpp.
Referenced by mx::astro::solve_kepler_danby().
solve_kepler()
template<typename realT > long mx::astro::solve_kepler (realT & E, realT & D, realT e, realT M, realT tol = KEPLER_TOL, long itmax = KEPLER_ITMAX)
Solve Kepler's equation for any e. Uses solve_kepler_danby if e < 1.0, hyperbolic_kepler otherwise.
Returns
the number of iterations on success.
-1 if itmax is exceeded.
Parameters
[out] E is the eccentric anomaly
[out] D is the error after the last iteration
[in] e is the eccentricity
[in] M is the mean anomaly
[in] tol is the desired tolerance
[in] itmax is the maximum number of iterations
Definition at line 157 of file kepler.hpp.
References DAYSEC, DPI, mx::astro::hyperbolic_kepler(), KEPLER_ITMAX, KEPLER_TOL, and mx::astro::solve_kepler_danby().
Referenced by mx::astro::orbitElements().
solve_kepler_danby()
template<typename realT > long mx::astro::solve_kepler_danby (realT & E, realT & D, realT e, realT M, realT tol, long itmax)
Solve Kepler's equation using Danby's quartic Newton-Raphson method.
Returns
-1 on exceeding itmax.
the number of iterations on success.
Parameters
[out] E is the eccentric anomaly
[out] D is the error after the last iteration
[in] e is the eccentricity
[in] M is the mean anomaly
[in] tol is the desired tolerance
[in] itmax is the maximum number of iterations
Definition at line 117 of file kepler.hpp.
References mx::astro::kepler_danby_1().
Referenced by mx::astro::solve_kepler().