mxlib: General Mathematics
General Mathematics
General mathematical utilities.
General mathematical utilities.
Modules
Geometry and Geodesy
Functions for basic geometry and working with earth coordinate systems.
Special Functions
Various special functions.
Templatized BLAS and Lapack
Templatized interfaces to the BLAS and the Lapack library.
Interpolation
Various tools for interpolating data and discrete functions.
Data Fitting
Tools for fitting functions to data.
Random Numbers
Random number generation.
Vector Utilities
Utilities for working with std::vector.
Gen. Math Files
Source files for General Mathematics.
Functions
template<typename dataT >
int mx::eigenGESDD (Eigen::Array< dataT,-1,-1 > &U, Eigen::Array< dataT,-1,-1 > &S, Eigen::Array< dataT,-1,-1 > &VT, Eigen::Array< dataT,-1,-1 > &A)
Compute the SVD of an Eigen::Array using LAPACK's xgesdd.
template<typename dataT >
int mx::eigenPseudoInverse (Eigen::Array< dataT, -1, -1 > &PInv, dataT &condition, int &nRejected, Eigen::Array< dataT, -1, -1 > &U, Eigen::Array< dataT, -1, -1 > &S, Eigen::Array< dataT, -1, -1 > &VT, Eigen::Array< dataT, -1, -1 > &A, dataT &maxCondition, int interact=MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
template<typename dataT >
int mx::eigenPseudoInverse (Eigen::Array< dataT, -1, -1 > &PInv, dataT &condition, int &nRejected, Eigen::Array< dataT, -1, -1 > &A, dataT &maxCondition, int interact=MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
template<typename realT >
void mx::quarticRoots (std::vector< std::complex< realT > > &x, realT a, realT b, realT c, realT d, realT e)
Find the roots of the general quartic equation.
Function Documentation
eigenGESDD()
template<typename dataT > int mx::eigenGESDD (Eigen::Array< dataT,-1,-1 > & U, Eigen::Array< dataT,-1,-1 > & S, Eigen::Array< dataT,-1,-1 > & VT, Eigen::Array< dataT,-1,-1 > & A)
Compute the SVD of an Eigen::Array using LAPACK's xgesdd.
Computes the SVD of A, \(A = U S V^T \).
Parameters
[out] U the A.rows() x A.rows() left matrix
[out] S the A.cols() x 1 matrix of singular values
[out] VT the A.cols() x A.cols() right matrix, note this is the transpose.
[in] A the input matrix to be decomposed
Returns
0 on success -i on error in ith parameter (from LAPACK xgesdd) >0 did not converge (from LAPACK xgesdd)
Template Parameters
dataT is either float or double.
Definition at line 458 of file eigenUtils.hpp.
Referenced by mx::eigenPseudoInverse().
eigenPseudoInverse() [1/2]
template<typename dataT > int mx::eigenPseudoInverse (Eigen::Array< dataT, -1, -1 > & PInv, dataT & condition, int & nRejected, Eigen::Array< dataT, -1, -1 > & U, Eigen::Array< dataT, -1, -1 > & S, Eigen::Array< dataT, -1, -1 > & VT, Eigen::Array< dataT, -1, -1 > & A, dataT & maxCondition, int interact = MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
First computes the SVD of A, \(A = U S V^T \), using eigenGESDD. Then the psuedo-inverse is calculated as \(A^+ = V S^+ U^T\).
Parameters
[out] PInv the pseudo-inverse of A
[out] condition The final condition number.
[out] nRejected the number of eigenvectors rejected
[out] U
[out] S
[out] VT
[in] A the matrix to invert
[in] maxCondition he maximum condition number desired, which is used to threshold the singular values. Set to 0 use include all eigenvalues/vectors. This is ignored if interactive.
[in] interact [optional] a bitmask controlling interaction. If (interact & MX_PINV_PLOT) is true, then gnuPlot is used to display the singular values. If (interact & MX_PINV_ASK) is true then the minimum singular value threshold is requested from the user using stdin.
Template Parameters
dataT is either float or double.
Definition at line 513 of file eigenUtils.hpp.
References mx::gnuPlot::command(), mx::eigenGESDD(), mx::gnuPlot::logy(), mx::gnuPlot::plot(), and mx::astro::constants::sigma().
Referenced by mx::eigenPseudoInverse(), and mx::AO::ifPInv().
eigenPseudoInverse() [2/2]
template<typename dataT > int mx::eigenPseudoInverse (Eigen::Array< dataT, -1, -1 > & PInv, dataT & condition, int & nRejected, Eigen::Array< dataT, -1, -1 > & A, dataT & maxCondition, int interact = MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
First computes the SVD of A, \(A = U S V^T \), using eigenGESDD. Then the psuedo-inverse is calculated as \(A^+ = V S^+ U^T\). This interface does not provide access to U, S and VT.
Parameters
PInv [out] the pseudo-inverse of A
condition [out] The final condition number.
nRejected [out] the number of eigenvectors rejected
A [in] the matrix to invert
maxCondition [in] the maximum condition number desired, whichis used to threshold the singular values. Set to 0 use include all eigenvalues/vectors. This is ignored if interactive.
interact [in] [optional] a bitmask controlling interaction. If (interact & MX_PINV_PLOT) is true, then gnuPlot is used to display the eigenvalues. If (interact & MX_PINV_ASK) is true then the minimum eigenvaue threshold is requested from the user using stdin.
Template Parameters
dataT is either float or double.
Definition at line 633 of file eigenUtils.hpp.
References mx::eigenPseudoInverse().
quarticRoots()
template<typename realT > void mx::quarticRoots (std::vector< std::complex< realT > > & x, realT a, realT b, realT c, realT d, realT e)
Find the roots of the general quartic equation.
Finds the roots of
\[ f(x) = a x^4 + b x^3 + c x^2 + d x + e \]
using the general formula for quartic roots. See https://en.wikipedia.org/wiki/Quartic_function.
Parameters
[out] x is resized to length 4, and on exit contains the 4 roots.
[in] a is the coefficient of the \(x^4\) term.
[in] b is the coefficient of the \(x^3\) term.
[in] c is the coefficient of the \(x^2\) term.
[in] d is the coefficient of the \(x^1\) term.
[in] e is the coefficient of the \(x^0\) term.
Template Parameters
realT is the floating point type used for calculations.
Definition at line 38 of file roots.hpp.