var hierarchy =
[
    [ "mx::improc::ADIDerotator< _realT >", "structmx_1_1improc_1_1ADIDerotator.html", null ],
    [ "mx::AO::aoAtmosphere< _realT >", "classmx_1_1AO_1_1aoAtmosphere.html", null ],
    [ "mx::AO::aoAtmosphere< realT >", "classmx_1_1AO_1_1aoAtmosphere.html", null ],
    [ "mx::AO::aoSystem< realT, inputSpectT, wfsBetaT >", "classmx_1_1AO_1_1aoSystem.html", null ],
    [ "mx::appConfigurator", "structmx_1_1appConfigurator.html", null ],
    [ "mx::application", "classmx_1_1application.html", null ],
    [ "mx::array2Fit< floatT >", "structmx_1_1array2Fit.html", null ],
    [ "mx::array2Fit< float >", "structmx_1_1array2Fit.html", null ],
    [ "mx::autocorrelationFromPSD< T >", "structmx_1_1autocorrelationFromPSD.html", null ],
    [ "mx::autocorrelationFromPSD< realT >", "structmx_1_1autocorrelationFromPSD.html", null ],
    [ "mx::improc::azBoxKernel< _arrayT, _kernW >", "structmx_1_1improc_1_1azBoxKernel.html", null ],
    [ "mx::improc::bilinearTransform< _arithT >", "structmx_1_1improc_1_1bilinearTransform.html", null ],
    [ "mx::astro::calspecSpectrum< _units >", "structmx_1_1astro_1_1calspecSpectrum.html", null ],
    [ "mx::AO::sim::ccdDetector< _floatT >", "classmx_1_1AO_1_1sim_1_1ccdDetector.html", null ],
    [ "mx::astro::units::cgs< _realT >", "structmx_1_1astro_1_1units_1_1cgs.html", null ],
    [ "mx::AO::clGainOpt< _realT >", "structmx_1_1AO_1_1clGainOpt.html", null ],
    [ "mx::AO::clGainOpt< realT >", "structmx_1_1AO_1_1clGainOpt.html", null ],
    [ "mx::AO::clGainOptOptGain_OL< realT >", "structmx_1_1AO_1_1clGainOptOptGain__OL.html", null ],
    [ "mx::AO::clMaxStableGainOpt< realT >", "structmx_1_1AO_1_1clMaxStableGainOpt.html", null ],
    [ "mx::clOptions", "structmx_1_1clOptions.html", null ],
    [ "mx::configTarget", "structmx_1_1configTarget.html", null ],
    [ "mx::improc::cubicConvolTransform< _arithT >", "structmx_1_1improc_1_1cubicConvolTransform.html", null ],
    [ "mx::AO::sim::directPhaseReconstructor< realT >", "classmx_1_1AO_1_1sim_1_1directPhaseReconstructor.html", null ],
    [ "mx::improc::ds9Interface", "classmx_1_1improc_1_1ds9Interface.html", null ],
    [ "mx::astro::units::earth< _realT >", "structmx_1_1astro_1_1units_1_1earth.html", null ],
    [ "mx::eigenArrPlanes< arrT, isCube >", "structmx_1_1eigenArrPlanes.html", null ],
    [ "mx::improc::eigenCube< dataT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::improc::eigenCube< realT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::fftT< _inputT, _outputT, _dim, 0 >", "classmx_1_1fftT_3_01__inputT_00_01__outputT_00_01__dim_00_010_01_4.html", null ],
    [ "mx::fftwPlanSpec< realT >", "structmx_1_1fftwPlanSpec.html", null ],
    [ "mx::fftwPlanSpec< __float128 >", "structmx_1_1fftwPlanSpec_3_01____float128_01_4.html", null ],
    [ "mx::fftwPlanSpec< double >", "structmx_1_1fftwPlanSpec_3_01double_01_4.html", null ],
    [ "mx::fftwPlanSpec< float >", "structmx_1_1fftwPlanSpec_3_01float_01_4.html", null ],
    [ "mx::fftwPlanSpec< long double >", "structmx_1_1fftwPlanSpec_3_01long_01double_01_4.html", null ],
    [ "mx::fftwTypeSpec< _inputDataT, _outputDataT >", "structmx_1_1fftwTypeSpec.html", null ],
    [ "mx::fftwTypeSpec< __float128, complexQT >", "structmx_1_1fftwTypeSpec_3_01____float128_00_01complexQT_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexDT, complexDT >", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01complexDT_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexDT, double >", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01double_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexFT, complexFT >", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01complexFT_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexFT, float >", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01float_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexLT, complexLT >", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01complexLT_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexLT, long double >", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01long_01double_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexQT, __float128 >", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01____float128_01_4.html", null ],
    [ "mx::fftwTypeSpec< complexQT, complexQT >", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01complexQT_01_4.html", null ],
    [ "mx::fftwTypeSpec< double, complexDT >", "structmx_1_1fftwTypeSpec_3_01double_00_01complexDT_01_4.html", null ],
    [ "mx::fftwTypeSpec< float, complexFT >", "structmx_1_1fftwTypeSpec_3_01float_00_01complexFT_01_4.html", null ],
    [ "mx::fftwTypeSpec< long double, complexLT >", "structmx_1_1fftwTypeSpec_3_01long_01double_00_01complexLT_01_4.html", null ],
    [ "mx::improc::fitsFile< dataT >", "classmx_1_1improc_1_1fitsFile.html", null ],
    [ "mx::improc::fitsHeader", "classmx_1_1improc_1_1fitsHeader.html", null ],
    [ "mx::improc::fitsHeaderCard", "structmx_1_1improc_1_1fitsHeaderCard.html", null ],
    [ "mx::AO::fourierCovariance< floatT, aosysT >", "structmx_1_1AO_1_1fourierCovariance.html", null ],
    [ "mx::fourierModeDef", "structmx_1_1fourierModeDef.html", null ],
    [ "mx::AO::fourierTemporalPSD< realT, aosysT >", "structmx_1_1AO_1_1fourierTemporalPSD.html", null ],
    [ "mx::wfp::fraunhoferPropagator< _wavefrontT >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::wfp::fraunhoferPropagator< complexFieldT >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::gaussian2D_gen_fitter< _floatT >", "structmx_1_1gaussian2D__gen__fitter.html", null ],
    [ "mx::gaussian2D_gen_fitter< realT >", "structmx_1_1gaussian2D__gen__fitter.html", null ],
    [ "mx::gaussian2D_sym_fitter< _floatT >", "structmx_1_1gaussian2D__sym__fitter.html", null ],
    [ "mx::improc::gaussKernel< _arrayT, _kernW >", "structmx_1_1improc_1_1gaussKernel.html", null ],
    [ "mx::AO::sim::generalIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1generalIntegrator.html", null ],
    [ "mx::gnuPlot", "classmx_1_1gnuPlot.html", null ],
    [ "mx::hasJacobian< T >", "structmx_1_1hasJacobian.html", null ],
    [ "mx::improc::HCIobservation< _realT >", "structmx_1_1improc_1_1HCIobservation.html", [
      [ "mx::improc::ADIobservation< _realT, _derotFunctObj >", "structmx_1_1improc_1_1ADIobservation.html", [
        [ "mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >", "structmx_1_1improc_1_1KLIPreduction.html", null ]
      ] ]
    ] ],
    [ "mx::wfp::idealCoronagraph< _realT >", "structmx_1_1wfp_1_1idealCoronagraph.html", null ],
    [ "mx::improc::imCenterCircleSym< realT >", "structmx_1_1improc_1_1imCenterCircleSym.html", null ],
    [ "mx::is_eigenCube< T >", "structmx_1_1is__eigenCube.html", null ],
    [ "mx::is_imagingArray< T >", "structmx_1_1is__imagingArray.html", null ],
    [ "mx::meta::is_std_vector< T, if_value_type >", "structmx_1_1meta_1_1is__std__vector.html", null ],
    [ "mx::meta::is_std_vector< T, false >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01false_01_4.html", null ],
    [ "mx::meta::is_std_vector< T, true >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01true_01_4.html", null ],
    [ "mx::astro::units::jupiter< _realT >", "structmx_1_1astro_1_1units_1_1jupiter.html", null ],
    [ "mx::laplace_distribution< _RealType >", "classmx_1_1laplace__distribution.html", null ],
    [ "mx::AO::sim::leakyIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1leakyIntegrator.html", null ],
    [ "mx::levmarInterface< fitterT >", "classmx_1_1levmarInterface.html", [
      [ "mx::fitGaussian2D< fitterT >", "classmx_1_1fitGaussian2D.html", null ]
    ] ],
    [ "mx::levmarInterface< mx::gaussian2D_gen_fitter< realT > >", "classmx_1_1levmarInterface.html", [
      [ "mx::fitGaussian2D< mx::gaussian2D_gen_fitter< realT > >", "classmx_1_1fitGaussian2D.html", null ]
    ] ],
    [ "mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >", "structmx_1_1wfp_1_1lyotCoronagraph.html", null ],
    [ "mx::astro::mainSequence< realT >", "structmx_1_1astro_1_1mainSequence.html", null ],
    [ "msgq", "structmsgq.html", null ],
    [ "msgq_textmsg", "structmsgq__textmsg.html", null ],
    [ "mxException", "classmxException.html", null ],
    [ "mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >", "classmx_1_1ompLoopWatcher.html", null ],
    [ "mx::laplace_distribution< _RealType >::param_type", "structmx_1_1laplace__distribution_1_1param__type.html", null ],
    [ "mx::psdFilter< _realT >", "classmx_1_1psdFilter.html", null ],
    [ "mx::psdFilter< realT >", "classmx_1_1psdFilter.html", null ],
    [ "mx::AO::sim::pywfsSlopeReconstructor< _floatT >", "classmx_1_1AO_1_1sim_1_1pywfsSlopeReconstructor.html", null ],
    [ "mx::AO::pywfsUnmod< floatT >", "structmx_1_1AO_1_1pywfsUnmod.html", null ],
    [ "mx::randomT< typeT, _ranengT, _randistT >", "classmx_1_1randomT.html", null ],
    [ "mx::randomT< floatT, std::mt19937_64, std::gamma_distribution< floatT > >", "classmx_1_1randomT.html", null ],
    [ "mx::randomT< floatT, std::mt19937_64, std::normal_distribution< floatT > >", "classmx_1_1randomT.html", null ],
    [ "mx::randomT< int, std::mt19937_64, std::poisson_distribution< int > >", "classmx_1_1randomT.html", null ],
    [ "mx::randomT< realT >", "classmx_1_1randomT.html", null ],
    [ "sharedmem_segment", "structsharedmem__segment.html", null ],
    [ "sharedMemSegment", "classsharedMemSegment.html", null ],
    [ "mx::astro::units::si< _realT >", "structmx_1_1astro_1_1units_1_1si.html", null ],
    [ "mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >", "classmx_1_1AO_1_1sim_1_1simulatedAOSystem.html", null ],
    [ "mx::astro::units::solar< _realT >", "structmx_1_1astro_1_1units_1_1solar.html", null ],
    [ "mx::syevrMem< sizeT, intT, floatT >", "structmx_1_1syevrMem.html", null ],
    [ "mx::textTable", "structmx_1_1textTable.html", null ],
    [ "mx::meta::trueFalseT< trueFalse >", "structmx_1_1meta_1_1trueFalseT.html", null ],
    [ "mx::meta::trueFalseT< false >", "structmx_1_1meta_1_1trueFalseT_3_01false_01_4.html", null ],
    [ "mx::meta::trueFalseT< true >", "structmx_1_1meta_1_1trueFalseT_3_01true_01_4.html", [
      [ "mx::meta::has_value_type< T, void_t< typename T::value_type > >", "structmx_1_1meta_1_1has__value__type_3_01T_00_01void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ]
    ] ],
    [ "mx::AO::sim::turbAtmosphere< _realT >", "structmx_1_1AO_1_1sim_1_1turbAtmosphere.html", null ],
    [ "mx::AO::sim::turbLayer< _realT >", "structmx_1_1AO_1_1sim_1_1turbLayer.html", null ],
    [ "mx::AO::vonKarmanSpectrum< floatT >", "structmx_1_1AO_1_1vonKarmanSpectrum.html", null ],
    [ "mx::AO::sim::wavefront< _realT >", "structmx_1_1AO_1_1sim_1_1wavefront.html", null ]
];