var namespacemx =
[
    [ "AO", null, [
      [ "beta_p", "namespacemx_1_1AO_1_1beta__p.html", "namespacemx_1_1AO_1_1beta__p" ],
      [ "path", "namespacemx_1_1AO_1_1path.html", null ],
      [ "sim", null, [
        [ "ccdDetector", "classmx_1_1AO_1_1sim_1_1ccdDetector.html", "classmx_1_1AO_1_1sim_1_1ccdDetector" ],
        [ "directPhaseReconstructor", "classmx_1_1AO_1_1sim_1_1directPhaseReconstructor.html", "classmx_1_1AO_1_1sim_1_1directPhaseReconstructor" ],
        [ "generalIntegrator", "classmx_1_1AO_1_1sim_1_1generalIntegrator.html", "classmx_1_1AO_1_1sim_1_1generalIntegrator" ],
        [ "leakyIntegrator", "classmx_1_1AO_1_1sim_1_1leakyIntegrator.html", "classmx_1_1AO_1_1sim_1_1leakyIntegrator" ],
        [ "pywfsSlopeReconstructor", "classmx_1_1AO_1_1sim_1_1pywfsSlopeReconstructor.html", "classmx_1_1AO_1_1sim_1_1pywfsSlopeReconstructor" ],
        [ "simulatedAOSystem", "classmx_1_1AO_1_1sim_1_1simulatedAOSystem.html", "classmx_1_1AO_1_1sim_1_1simulatedAOSystem" ],
        [ "turbAtmosphere", "structmx_1_1AO_1_1sim_1_1turbAtmosphere.html", "structmx_1_1AO_1_1sim_1_1turbAtmosphere" ],
        [ "turbLayer", "structmx_1_1AO_1_1sim_1_1turbLayer.html", "structmx_1_1AO_1_1sim_1_1turbLayer" ],
        [ "wavefront", "structmx_1_1AO_1_1sim_1_1wavefront.html", "structmx_1_1AO_1_1sim_1_1wavefront" ]
      ] ],
      [ "aoAtmosphere", "classmx_1_1AO_1_1aoAtmosphere.html", "classmx_1_1AO_1_1aoAtmosphere" ],
      [ "aoSystem", "classmx_1_1AO_1_1aoSystem.html", "classmx_1_1AO_1_1aoSystem" ],
      [ "clGainOpt", "structmx_1_1AO_1_1clGainOpt.html", "structmx_1_1AO_1_1clGainOpt" ],
      [ "clGainOptOptGain_OL", "structmx_1_1AO_1_1clGainOptOptGain__OL.html", null ],
      [ "clMaxStableGainOpt", "structmx_1_1AO_1_1clMaxStableGainOpt.html", null ],
      [ "fourierCovariance", "structmx_1_1AO_1_1fourierCovariance.html", "structmx_1_1AO_1_1fourierCovariance" ],
      [ "fourierTemporalPSD", "structmx_1_1AO_1_1fourierTemporalPSD.html", "structmx_1_1AO_1_1fourierTemporalPSD" ],
      [ "vonKarmanSpectrum", "structmx_1_1AO_1_1vonKarmanSpectrum.html", "structmx_1_1AO_1_1vonKarmanSpectrum" ]
    ] ],
    [ "astro", null, [
      [ "units", null, [
        [ "cgs", "structmx_1_1astro_1_1units_1_1cgs.html", "structmx_1_1astro_1_1units_1_1cgs" ],
        [ "earth", "structmx_1_1astro_1_1units_1_1earth.html", "structmx_1_1astro_1_1units_1_1earth" ],
        [ "jupiter", "structmx_1_1astro_1_1units_1_1jupiter.html", "structmx_1_1astro_1_1units_1_1jupiter" ],
        [ "si", "structmx_1_1astro_1_1units_1_1si.html", "structmx_1_1astro_1_1units_1_1si" ],
        [ "solar", "structmx_1_1astro_1_1units_1_1solar.html", "structmx_1_1astro_1_1units_1_1solar" ]
      ] ],
      [ "calspecSpectrum", "structmx_1_1astro_1_1calspecSpectrum.html", "structmx_1_1astro_1_1calspecSpectrum" ],
      [ "mainSequence", "structmx_1_1astro_1_1mainSequence.html", "structmx_1_1astro_1_1mainSequence" ]
    ] ],
    [ "improc", null, [
      [ "ADIDerotator", "structmx_1_1improc_1_1ADIDerotator.html", "structmx_1_1improc_1_1ADIDerotator" ],
      [ "ADIobservation", "structmx_1_1improc_1_1ADIobservation.html", "structmx_1_1improc_1_1ADIobservation" ],
      [ "azBoxKernel", "structmx_1_1improc_1_1azBoxKernel.html", null ],
      [ "bilinearTransform", "structmx_1_1improc_1_1bilinearTransform.html", null ],
      [ "cubicConvolTransform", "structmx_1_1improc_1_1cubicConvolTransform.html", null ],
      [ "ds9Interface", "classmx_1_1improc_1_1ds9Interface.html", "classmx_1_1improc_1_1ds9Interface" ],
      [ "eigenCube", "classmx_1_1improc_1_1eigenCube.html", "classmx_1_1improc_1_1eigenCube" ],
      [ "fitsFile", "classmx_1_1improc_1_1fitsFile.html", "classmx_1_1improc_1_1fitsFile" ],
      [ "fitsHeader", "classmx_1_1improc_1_1fitsHeader.html", "classmx_1_1improc_1_1fitsHeader" ],
      [ "fitsHeaderCard", "structmx_1_1improc_1_1fitsHeaderCard.html", "structmx_1_1improc_1_1fitsHeaderCard" ],
      [ "gaussKernel", "structmx_1_1improc_1_1gaussKernel.html", null ],
      [ "HCIobservation", "structmx_1_1improc_1_1HCIobservation.html", "structmx_1_1improc_1_1HCIobservation" ],
      [ "imCenterCircleSym", "structmx_1_1improc_1_1imCenterCircleSym.html", "structmx_1_1improc_1_1imCenterCircleSym" ],
      [ "KLIPreduction", "structmx_1_1improc_1_1KLIPreduction.html", "structmx_1_1improc_1_1KLIPreduction" ]
    ] ],
    [ "meta", null, [
      [ "has_value_type< T, void_t< typename T::value_type > >", "structmx_1_1meta_1_1has__value__type_3_01T_00_01void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ],
      [ "is_std_vector", "structmx_1_1meta_1_1is__std__vector.html", null ],
      [ "is_std_vector< T, false >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01false_01_4.html", null ],
      [ "is_std_vector< T, true >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01true_01_4.html", null ],
      [ "trueFalseT", "structmx_1_1meta_1_1trueFalseT.html", null ],
      [ "trueFalseT< false >", "structmx_1_1meta_1_1trueFalseT_3_01false_01_4.html", "structmx_1_1meta_1_1trueFalseT_3_01false_01_4" ],
      [ "trueFalseT< true >", "structmx_1_1meta_1_1trueFalseT_3_01true_01_4.html", "structmx_1_1meta_1_1trueFalseT_3_01true_01_4" ]
    ] ],
    [ "sigproc", null, [
      [ "psdFilter", "classmx_1_1sigproc_1_1psdFilter.html", "classmx_1_1sigproc_1_1psdFilter" ]
    ] ],
    [ "wfp", null, [
      [ "fraunhoferPropagator", "classmx_1_1wfp_1_1fraunhoferPropagator.html", "classmx_1_1wfp_1_1fraunhoferPropagator" ],
      [ "idealCoronagraph", "structmx_1_1wfp_1_1idealCoronagraph.html", "structmx_1_1wfp_1_1idealCoronagraph" ],
      [ "lyotCoronagraph", "structmx_1_1wfp_1_1lyotCoronagraph.html", "structmx_1_1wfp_1_1lyotCoronagraph" ]
    ] ],
    [ "appConfigurator", "structmx_1_1appConfigurator.html", "structmx_1_1appConfigurator" ],
    [ "application", "classmx_1_1application.html", "classmx_1_1application" ],
    [ "array2Fit", "structmx_1_1array2Fit.html", "structmx_1_1array2Fit" ],
    [ "autocorrelationFromPSD", "structmx_1_1autocorrelationFromPSD.html", "structmx_1_1autocorrelationFromPSD" ],
    [ "clOptions", "structmx_1_1clOptions.html", "structmx_1_1clOptions" ],
    [ "configTarget", "structmx_1_1configTarget.html", "structmx_1_1configTarget" ],
    [ "eigenArrPlanes", "structmx_1_1eigenArrPlanes.html", null ],
    [ "fftT< _inputT, _outputT, _dim, 0 >", "classmx_1_1fftT_3_01__inputT_00_01__outputT_00_01__dim_00_010_01_4.html", "classmx_1_1fftT_3_01__inputT_00_01__outputT_00_01__dim_00_010_01_4" ],
    [ "fftwPlanSpec", "structmx_1_1fftwPlanSpec.html", "structmx_1_1fftwPlanSpec" ],
    [ "fftwPlanSpec< __float128 >", "structmx_1_1fftwPlanSpec_3_01____float128_01_4.html", "structmx_1_1fftwPlanSpec_3_01____float128_01_4" ],
    [ "fftwPlanSpec< double >", "structmx_1_1fftwPlanSpec_3_01double_01_4.html", "structmx_1_1fftwPlanSpec_3_01double_01_4" ],
    [ "fftwPlanSpec< float >", "structmx_1_1fftwPlanSpec_3_01float_01_4.html", "structmx_1_1fftwPlanSpec_3_01float_01_4" ],
    [ "fftwPlanSpec< long double >", "structmx_1_1fftwPlanSpec_3_01long_01double_01_4.html", "structmx_1_1fftwPlanSpec_3_01long_01double_01_4" ],
    [ "fftwTypeSpec", "structmx_1_1fftwTypeSpec.html", "structmx_1_1fftwTypeSpec" ],
    [ "fftwTypeSpec< __float128, complexQT >", "structmx_1_1fftwTypeSpec_3_01____float128_00_01complexQT_01_4.html", "structmx_1_1fftwTypeSpec_3_01____float128_00_01complexQT_01_4" ],
    [ "fftwTypeSpec< complexDT, complexDT >", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01complexDT_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01complexDT_01_4" ],
    [ "fftwTypeSpec< complexDT, double >", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01double_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexDT_00_01double_01_4" ],
    [ "fftwTypeSpec< complexFT, complexFT >", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01complexFT_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01complexFT_01_4" ],
    [ "fftwTypeSpec< complexFT, float >", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01float_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexFT_00_01float_01_4" ],
    [ "fftwTypeSpec< complexLT, complexLT >", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01complexLT_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01complexLT_01_4" ],
    [ "fftwTypeSpec< complexLT, long double >", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01long_01double_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexLT_00_01long_01double_01_4" ],
    [ "fftwTypeSpec< complexQT, __float128 >", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01____float128_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01____float128_01_4" ],
    [ "fftwTypeSpec< complexQT, complexQT >", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01complexQT_01_4.html", "structmx_1_1fftwTypeSpec_3_01complexQT_00_01complexQT_01_4" ],
    [ "fftwTypeSpec< double, complexDT >", "structmx_1_1fftwTypeSpec_3_01double_00_01complexDT_01_4.html", "structmx_1_1fftwTypeSpec_3_01double_00_01complexDT_01_4" ],
    [ "fftwTypeSpec< float, complexFT >", "structmx_1_1fftwTypeSpec_3_01float_00_01complexFT_01_4.html", "structmx_1_1fftwTypeSpec_3_01float_00_01complexFT_01_4" ],
    [ "fftwTypeSpec< long double, complexLT >", "structmx_1_1fftwTypeSpec_3_01long_01double_00_01complexLT_01_4.html", "structmx_1_1fftwTypeSpec_3_01long_01double_00_01complexLT_01_4" ],
    [ "fitGaussian2D", "classmx_1_1fitGaussian2D.html", null ],
    [ "fourierModeDef", "structmx_1_1fourierModeDef.html", "structmx_1_1fourierModeDef" ],
    [ "gaussian2D_gen_fitter", "structmx_1_1gaussian2D__gen__fitter.html", null ],
    [ "gaussian2D_sym_fitter", "structmx_1_1gaussian2D__sym__fitter.html", null ],
    [ "gnuPlot", "classmx_1_1gnuPlot.html", "classmx_1_1gnuPlot" ],
    [ "hasJacobian", "structmx_1_1hasJacobian.html", "structmx_1_1hasJacobian" ],
    [ "is_eigenCube", "structmx_1_1is__eigenCube.html", null ],
    [ "is_imagingArray", "structmx_1_1is__imagingArray.html", null ],
    [ "laplace_distribution", "classmx_1_1laplace__distribution.html", "classmx_1_1laplace__distribution" ],
    [ "levmarInterface", "classmx_1_1levmarInterface.html", "classmx_1_1levmarInterface" ],
    [ "ompLoopWatcher", "classmx_1_1ompLoopWatcher.html", "classmx_1_1ompLoopWatcher" ],
    [ "randomT", "classmx_1_1randomT.html", "classmx_1_1randomT" ],
    [ "syevrMem", "structmx_1_1syevrMem.html", null ],
    [ "textTable", "structmx_1_1textTable.html", "structmx_1_1textTable" ]
];