mxlib: mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT > Struct Template Reference
mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT > Struct Template Reference
Wavefront Propagation » Coronagraphs
template<typename _realT, typename _fpmaskFloatT>
struct mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >
The Lyot Coronagraph.
A generalized Lyot coronagraph, which can include a pupil apodization, a focal plane mask with complex transmission, and a Lyot stop. Light is propagated through the coronagraph plane-by-plane, and the complex wavefront can be accessed at any plane. Also provides functions for optimizing the pupil apodizer and focal plane mask.
Definition at line 36 of file lyotCoronagraph.hpp.
#include <lyotCoronagraph.hpp>
Public Types
typedef _realT realT
The real floating point type.
typedef _fpmaskFloatT fpmaskFloatT
The real floating point type for mask calculations.
typedef std::complex< realT > complexT
The complex floating point type.
typedef mx::imagingArray< std::complex< realT >, fftwAllocator< std::complex< realT > >, 0 > complexFieldT
The wavefront complex field type.
typedef Eigen::Array< fpmaskFloatT, Eigen::Dynamic, Eigen::Dynamic > fpMaskT
The focal plane mask type.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > imageT
The image type.
Public Member Functions
int wfSz ()
Get the wavefront size in pixels.
void wfSz (int sz)
Set the wavefront size in pixels.
void makeFocalMask (realT rad, fpmaskFloatT trans=0.0, int sz=0.0)
Make the focal plane mask.
void loadApodizer (const std::string &apodName)
Load the apodizer from a FITS file.
void loadFocalMask (const std::string &fpmName)
Load the focal plane mask from a FITS file.
void loadLyotStop (const std::string &lyotName)
Load the Lyot stop from a FITS file.
void loadCoronagraph (const std::string &cName)
Load the components of the coronagraph based in its base name.
void loadCoronagraph (const std::string &apodName, const std::string &fpmName, const std::string &lyotName)
Load the components of the coronagraph from FITS files.
void propagate (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
void propagateNC (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
void optimizeAPLCMC (imageT &geomPupil, realT fpmRadPix, realT relTol, realT absTol, int maxIter, const std::string &cname)
Optimize the pupil amplitude apodization and focal-plane mask complex transmission.
Public Attributes
std::string _fileDir
The directory where coronagraph files are stored.
int _wfSz
The linear size of the wavefront in pixels.
imageT pupilApodizer
Image containing the pupil apodization.
int maskSource
0= read frounobs8m_2048_128_fpm.fitsm file, 1 = constructed by makeFocalMask, 2 = trans optimized.
std::string maskFile
Name of file from which mask was loaded.
realT maskRad
Radius of mask if it was constructed.
realT maskTrans
Transmission of mask if it was constructed.
fpMaskT focalMask
The focal plane mask.
imageT lyotStop
Image containing the lyot stop.
fraunhoferPropagator< complexFieldT > fi
Fraunhofer propagator.
Member Function Documentation
loadApodizer()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer (const std::string & apodName)
Load the apodizer from a FITS file.
Parameters
apodName is the name of the FITS file
Definition at line 230 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
loadCoronagraph() [1/2]
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph (const std::string & cName)
Load the components of the coronagraph based in its base name.
Looks in "./coron/"
Parameters
cName is the base name of the coronagraph
Definition at line 260 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_fileDir, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop().
loadCoronagraph() [2/2]
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph (const std::string & apodName, const std::string & fpmName, const std::string & lyotName)
Load the components of the coronagraph from FITS files.
Parameters
apodName is the name of the FITS file
fpmName is the name of the FITS file
lyotName is the name of the FITS file
Definition at line 272 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop, and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer.
loadFocalMask()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask (const std::string & fpmName)
Load the focal plane mask from a FITS file.
Parameters
fpmName is the name of the FITS file
Definition at line 238 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskFile, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskRad, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskSource, and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskTrans.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
loadLyotStop()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop (const std::string & lyotName)
Load the Lyot stop from a FITS file.
Parameters
lyotName is the name of the FITS file
Definition at line 251 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
optimizeAPLCMC()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC (imageT & geomPupil, realT fpmRadPix, realT relTol, realT absTol, int maxIter, const std::string & cname)
Optimize the pupil amplitude apodization and focal-plane mask complex transmission.
Uses the algorithm in Guyon (2014) [5] for optimizing an Apodized-Pupil Lyot Complex Mask Coronagraph (APLCMC).
Parameters
geomPupil The geometric pupil mask, binary 1/0 transmission.
fpmRadPix The radius in pixels of the FPM.
relTol Relative tolerance for convergence.
absTol Absolute tolerance for convergence.
maxIter Maximum number of iterations to allow.
cname Name of coronagraph, used as base-name for output files in _fileDir.
Definition at line 384 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz, mx::wfp::circularPupil(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::makeComplexPupil(), mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer.
propagate()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagate (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is modified by the coronagraph.
Definition at line 345 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal().
propagateNC()
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagateNC (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
For a Lyot coronagraph, this applies the pupil apodization and Lyot stop, but not the FPM, to the given pupil-plane wavefront such that the result will produce the non-coronagraphic (off-axis) PSF.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is modified by the coronagraph.
Definition at line 370 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal().
wfSz() [1/2]
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz ()
Get the wavefront size in pixels.
Returns
the wavefront size in pixels
Definition at line 184 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz.
wfSz() [2/2]
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz (int sz)
Set the wavefront size in pixels.
Parameters
[in] sz is the new size
Definition at line 190 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
The documentation for this struct was generated from the following file:
lyotCoronagraph.hpp