mxlib: mx::AO::vonKarmanSpectrum< realT > Struct Template Reference
mx::AO::vonKarmanSpectrum< realT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT>
struct mx::AO::vonKarmanSpectrum< realT >
Manage calculations using the von Karman spatial power spectrum.
Definition at line 33 of file aoPSDs.hpp.
#include <ao/analysis/aoPSDs.hpp>
Public Member Functions
vonKarmanSpectrum ()
Default Constructor.
vonKarmanSpectrum (bool subP, bool subT, realT D)
Constructor specifying the parameters.
bool subPiston ()
Get the value of _subPiston.
void subPiston (bool sp)
Set the value of _subPiston.
bool subTipTilt ()
Get the value of _subTipTilt.
void subTipTilt (bool st)
Set the value of the _subTipTilt flag.
bool scintillation ()
Get the value of _scintillation.
void scintillation (bool sc)
Set the value of _scintillation.
bool component ()
Get the value of _component.
void component (int cc)
Set the value of _component.
realT D ()
Get the value of the diameter _D.
void D (realT nd)
Set the aperture diameter.
realT operator() (aoAtmosphere< realT > &atm, realT k, int n, realT sec_zeta)
Get the value of the PSD at spatial frequency k and a zenith distance.
realT operator() (aoAtmosphere< realT > &atm, realT k, realT lambda, int n, realT lambda_wfs, realT secZeta)
Get the value of the PSD at spatial frequency k and wavelength lambda, and a zenith distance, with a WFS at a different wavelength.
realT fittingError (aoAtmosphere< realT > &atm, realT d)
Get the fitting error for an actuator spacing d.
Protected Attributes
bool _subPiston
flag controlling whether piston is subtracted from the PSD. Default is true.
bool _subTipTilt
flag controlling whether tip and tilt are subtracted from the PSD. Default is false.
bool _scintillation
flag controlling whether or not scintillation is included
int _component
If _scintillation is true, this controls whether phase (0), amplitude (1), or dispersive contrast (2) is returned.
realT _D
Diameter used for piston and tip/tilt subtraction, in m. Default is 1 m.
Constructor & Destructor Documentation
vonKarmanSpectrum() [1/2]
template<typename realT > mx::AO::vonKarmanSpectrum< realT >::vonKarmanSpectrum () inline
Default Constructor.
Definition at line 50 of file aoPSDs.hpp.
vonKarmanSpectrum() [2/2]
template<typename realT > mx::AO::vonKarmanSpectrum< realT >::vonKarmanSpectrum (bool subP, bool subT, realT D) inline
Constructor specifying the parameters.
Parameters
[in] subP is the value of _subPiston.
[in] subT is the value of _subTipTilt.
[in] D is the value of _D.
Definition at line 64 of file aoPSDs.hpp.
Member Function Documentation
component() [1/2]
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::component () inline
Get the value of _component.
Returns
_component
Definition at line 131 of file aoPSDs.hpp.
component() [2/2]
template<typename realT > void mx::AO::vonKarmanSpectrum< realT >::component (int cc) inline
Set the value of _component.
Parameters
cc is the new value of _component
Definition at line 140 of file aoPSDs.hpp.
D() [1/2]
template<typename realT > realT mx::AO::vonKarmanSpectrum< realT >::D () inline
Get the value of the diameter _D.
Returns
_D, the diameter in m.
Definition at line 149 of file aoPSDs.hpp.
D() [2/2]
template<typename realT > void mx::AO::vonKarmanSpectrum< realT >::D (realT nd) inline
Set the aperture diameter.
nd is the new diameter in m.
Definition at line 158 of file aoPSDs.hpp.
fittingError()
template<typename realT > realT mx::AO::vonKarmanSpectrum< realT >::fittingError (aoAtmosphere< realT > & atm, realT d) inline
Get the fitting error for an actuator spacing d.
Parameters
atm gives the atmosphere parameters r_0 and L_0
d is the actuator spacing in m
Definition at line 263 of file aoPSDs.hpp.
References mx::AO::aoAtmosphere< _realT >::L_0(), and mx::AO::aoAtmosphere< _realT >::r_0().
operator()() [1/2]
template<typename realT > realT mx::AO::vonKarmanSpectrum< realT >::operator() (aoAtmosphere< realT > & atm, realT k, int n, realT sec_zeta) inline
Get the value of the PSD at spatial frequency k and a zenith distance.
Returns
the von Karman PSD at the specified spatial frequency.
-1 if an error occurs.
Parameters
[in] atm gives the atmosphere parameters r_0 and L_0.
[in] k is the spatial frequency in m^-1.
[in] sec_zeta is the secant of the zenith distance.
Definition at line 170 of file aoPSDs.hpp.
References mx::math::func::jinc(), mx::math::func::jinc2(), mx::AO::aoAtmosphere< _realT >::L_0(), MXE_PARAMNOTSET, mxError, and mx::AO::aoAtmosphere< _realT >::r_0().
operator()() [2/2]
template<typename realT > realT mx::AO::vonKarmanSpectrum< realT >::operator() (aoAtmosphere< realT > & atm, realT k, realT lambda, int n, realT lambda_wfs, realT secZeta) inline
Get the value of the PSD at spatial frequency k and wavelength lambda, and a zenith distance, with a WFS at a different wavelength.
Returns
the von Karman PSD at the specified spatial frequency for the specified wavelength.
-1 if an error occurs.
Parameters
[in] atm gives the atmosphere parameters r_0 and L_0.
[in] k is the spatial frequency in m^-1.
[in] lambda is the observation wavelength in m
[in] lambda_wfs is the wavefront measurement wavelength in m
[in] secZeta is the secant of the zenith distance
Definition at line 226 of file aoPSDs.hpp.
References mx::AO::aoAtmosphere< _realT >::lam_0(), mx::AO::aoAtmosphere< _realT >::X(), mx::AO::aoAtmosphere< _realT >::X_Z(), and mx::AO::aoAtmosphere< _realT >::Y().
scintillation() [1/2]
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::scintillation () inline
Get the value of _scintillation.
Returns
_scintillation
Definition at line 113 of file aoPSDs.hpp.
scintillation() [2/2]
template<typename realT > void mx::AO::vonKarmanSpectrum< realT >::scintillation (bool sc) inline
Set the value of _scintillation.
Parameters
sc is the new value of _scintillation
Definition at line 122 of file aoPSDs.hpp.
subPiston() [1/2]
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::subPiston () inline
Get the value of _subPiston.
Returns
_subPiston
Definition at line 78 of file aoPSDs.hpp.
subPiston() [2/2]
template<typename realT > void mx::AO::vonKarmanSpectrum< realT >::subPiston (bool sp) inline
Set the value of _subPiston.
Parameters
[in] sp is the new value of _subPiston
Definition at line 86 of file aoPSDs.hpp.
subTipTilt() [1/2]
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::subTipTilt () inline
Get the value of _subTipTilt.
Returns
the value of _subTipTilt.
Definition at line 95 of file aoPSDs.hpp.
subTipTilt() [2/2]
template<typename realT > void mx::AO::vonKarmanSpectrum< realT >::subTipTilt (bool st) inline
Set the value of the _subTipTilt flag.
Parameters
st is the new value of _subTipTilt.
Definition at line 104 of file aoPSDs.hpp.
Member Data Documentation
_component
template<typename realT > int mx::AO::vonKarmanSpectrum< realT >::_component protected
If _scintillation is true, this controls whether phase (0), amplitude (1), or dispersive contrast (2) is returned.
Definition at line 41 of file aoPSDs.hpp.
_D
template<typename realT > realT mx::AO::vonKarmanSpectrum< realT >::_D protected
Diameter used for piston and tip/tilt subtraction, in m. Default is 1 m.
Definition at line 43 of file aoPSDs.hpp.
_scintillation
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::_scintillation protected
flag controlling whether or not scintillation is included
Definition at line 40 of file aoPSDs.hpp.
_subPiston
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::_subPiston protected
flag controlling whether piston is subtracted from the PSD. Default is true.
Definition at line 37 of file aoPSDs.hpp.
_subTipTilt
template<typename realT > bool mx::AO::vonKarmanSpectrum< realT >::_subTipTilt protected
flag controlling whether tip and tilt are subtracted from the PSD. Default is false.
Definition at line 38 of file aoPSDs.hpp.
The documentation for this struct was generated from the following file:
ao/analysis/aoPSDs.hpp