mxlib: mx::AO::sim::turbLayer< _realT > Struct Template Reference
mx::AO::sim::turbLayer< _realT > Struct Template Reference
template<typename _realT>
struct mx::AO::sim::turbLayer< _realT >
Simulation of a single turbulent layer.
Todo:
document this
add facility for changing interpolator
Definition at line 35 of file turbLayer.hpp.
#include <ao/sim/turbLayer.hpp>
Public Member Functions
void shift (realT dt)
Shift to a timestep.
void initRandom ()
Seed the uniform deviation. Call this if you intend to use shiftRandom.
void shiftRandom (bool nofract=false)
Shift by a random amount using the uniform distribution.
Public Attributes
mx::uniDistT< realT > uniVar
Uniform deviate, used in shiftRandom.
Member Function Documentation
initRandom()
template<typename realT > void mx::AO::sim::turbLayer< realT >::initRandom ()
Seed the uniform deviation. Call this if you intend to use shiftRandom.
This only needs to be called once.
Definition at line 227 of file turbLayer.hpp.
References mx::AO::sim::turbLayer< _realT >::uniVar.
shift()
template<typename realT > void mx::AO::sim::turbLayer< realT >::shift (realT dt)
Shift to a timestep.
Parameters
[in] dt is the new timestep.
Definition at line 189 of file turbLayer.hpp.
References mx::improc::imageShift(), and mx::improc::imageShiftWP().
shiftRandom()
template<typename realT > void mx::AO::sim::turbLayer< realT >::shiftRandom (bool nofract = false)
Shift by a random amount using the uniform distribution.
Call initRandom() once before calling this method.
Parameters
[in] nofract if true then the fractional part is ignored, and only a whole-pixel shift is executed. Default=false
Definition at line 233 of file turbLayer.hpp.
References mx::improc::imageShift(), mx::improc::imageShiftWP(), and mx::AO::sim::turbLayer< _realT >::uniVar.
Member Data Documentation
uniVar
template<typename _realT > mx::uniDistT<realT> mx::AO::sim::turbLayer< _realT >::uniVar
Uniform deviate, used in shiftRandom.
Definition at line 69 of file turbLayer.hpp.
Referenced by mx::AO::sim::turbLayer< _realT >::initRandom(), and mx::AO::sim::turbLayer< _realT >::shiftRandom().
The documentation for this struct was generated from the following file:
ao/sim/turbLayer.hpp